### Test if app is running
GET http://localhost:8090/api/test

### Get single duck fact
GET http://localhost:8090/facts/duck/{{id}}

### Get random duck fact
GET http://localhost:8090/facts/duck/random

### CORS - Get random
GET http://localhost:8090/facts/duck/random
Origin: http://localhost:5173
