CREATE TABLE facts
(
    id     SERIAL PRIMARY KEY,
    type   VARCHAR(255) DEFAULT '' NOT NULL,
    text   TEXT         DEFAULT '' NOT NULL,
    length INTEGER      DEFAULT 0  NOT NULL
);

INSERT INTO facts (type, text, length)
VALUES ('duck',
        'Ducklings, like other waterfowl, learn to communicate with each other in the eggs and try to hatch at the same time.',
        111),
       ('duck',
        'Hybridization doesn''t occur in the wild often, but mallards tend to crossbreed with 40 different waterfowl species. The wood duck takes the close second with crossbreeding with as many as 20 other duck species.',
        197),
       ('duck',
        'Ducks, like other waterfowl, have as many as 12,000 separate muscles to control their feathers. They can use these to lift or compress feathers to dive underwater, show emotion, or regulate body heat.',
        186),
       ('duck',
        'A duck''s bill varies by species and relates to its function. Flat bills are used to consume plant materials, while pointed bills are used to catch and eat fish.',
        146),
       ('duck',
        'Ducks can swim when it''s cold out because the blood vessels in their feet are close together, preventing heat loss.',
        120),
       ('duck', 'EMF Ducks love you', 18),
       ('duck',
        'Female ducks and ducklings have plain plumage with dark feathers that form a pattern on their head and eyes. This helps to camouflage their eyes, which could be seen by predators or pecked at by other ducks.',
        211),
       ('duck', 'The fastest duck recorded was a red-breasted merganser, which achieved an airspeed of 100 mph.', 93),
       ('duck',
        'Wood ducks are the only North American waterfowl that can raise two broods in one year. More than 11% of females may produce two broods each season.',
        155),
       ('duck',
        'Ducklings can understand the relationship between objects, which demonstrates abstract thought capabilities.',
        102),
       ('duck',
        'Ducks can move each eye independently and they store information on the opposite sides of their brain.', 91),
       ('duck', 'Ducks can sleep with one eye open to watch for predators.', 56),
       ('duck', 'According to research, ducks may show a preference for colors in the green or blue spectrum.', 89),
       ('duck',
        'Duckbills are sensitive and have many touch receptors, making them similar to our fingertips and palms.', 94),
       ('duck',
        'In 1940, a U.S. Fish and Wildlife Service biologist observed the largest concentration of ducks surveyed from the air on Catahoula Lake in Louisiana. He claimed to see as many as 8 million ducks.',
        193),
       ('duck',
        'The spectacled elder''s wintering grounds weren''t discovered until 1995, when researchers followed birds marked with satellite transmitters into the Bering Sea. Once there, they found a huge number of elders gathering in the fissures on the ice.',
        235),
       ('duck',
        'Fulvous whistling-ducks are found in Mexico and parts of the southern US, as well as southern Africa. It''s believed that the African population was carried to North America by strong winds.',
        182),
       ('duck',
        'Mallards often have clutches that include eggs fertilized by different males, which biologists believe ensures successful fertilization and greater genetic variation.',
        167),
       ('duck',
        'Ruddy ducks produce the largest eggs relative to their body size. Ruddy duck eggs can weigh more than the hen.',
        111),
       ('duck', 'City ducks have a different accent than country ducks - typically louder!', 72),
       ('duck', 'Ducks have exceptional visuals and can see finer detail at farther distances than humans.', 84),
       ('duck',
        'Some of the highest densities of nesting ducks occur in the San Luis Valley of Colorado, where some habitats support as many as 1,000 breeding ducks per square mile.',
        171),
       ('duck', 'Ducks migrate at an altitude of 200 to 4,000 feet but are capable of reaching heights of 21,000 feet.',
        98),
       ('duck',
        'Waterfowl spawned the Gold Rush. Birds eat stone, gravel, and sand to grind up hard foods, which they store in their gizzard. The Gold Rush was spurred in Nebraska when hunters found gold nuggets in the gizzards of ducks.',
        198),
       ('duck',
        'All ducks can dive, but some species are better at diving than others. The best is the long-tailed duck, also known as an oldsquaw, which can dive 240 feet.',
        154),
       ('duck',
        'Severe weather can trigger a mass migration known as a “grand passage.” In 1995, a blizzard in the Prairie Pothole Region spurred a migration of millions of ducks and geese that jammed radar systems and ground flights in Nebraska and Missouri.',
        238),
       ('duck', 'The oldest duck to be taken by a hunter was a 29-year-old canvasback.', 68),
       ('duck',
        'Wood ducks eat acorns. In a study conducted on captive wood ducks, the birds preferred willow oak acorns over acorns from other oak accords.',
        137),
       ('duck',
        'In a study of breeding mallards conducted by the Canadian Wildlife Service, the ducklings that hatch in the first 5 days of the period account for 40% of the first-year hens that survived to breed the following year.',
        202),
       ('duck',
        'In 1973, hundreds of ducks rained down from the sky in Stuttgart, AK. The ducks were likely killed by hail, but some had ice on their wings that may have accumulated when the wind carried them to high altitudes. The ducks falling damaged cars and windows.',
        243),
       ('duck',
        'Several ducks and other waterfowl practice nest parasitism, which is when the female lays eggs in the nests of other females in the same species.',
        141),
       ('duck',
        'The Labrador duck is the only known extinct North American waterfowl species, which is believed to have gone extinct in 1875 off Long Island, NY.',
        148),
       ('duck',
        'Harlequin ducks nest in rocky crevices along streams and dive to the bottom of the roaring water to feed on invertebrates. When they''re done, they walk upstream.',
        157);
